-- Banco inicial de questões autorais do Revisa.
-- Conteúdo demonstrativo criado para validar o fluxo do produto.

insert into public.revisa_questions
  (subject, topic, statement, alternatives, correct_answer, explanation, difficulty, active)
values
  ('Matemática','Porcentagem','Quanto é 15% de 200?',
    '[{"key":"A","text":"20"},{"key":"B","text":"30"},{"key":"C","text":"40"},{"key":"D","text":"50"}]'::jsonb,
    'B','15% de 200 = 0,15 × 200 = 30.',1,true),
  ('Matemática','Equação do 1º grau','Se x + 7 = 19, qual é o valor de x?',
    '[{"key":"A","text":"10"},{"key":"B","text":"11"},{"key":"C","text":"12"},{"key":"D","text":"13"}]'::jsonb,
    'C','Subtraindo 7 dos dois lados, x = 12.',1,true),
  ('Matemática','Média aritmética','Qual é a média de 6, 8 e 10?',
    '[{"key":"A","text":"7"},{"key":"B","text":"8"},{"key":"C","text":"9"},{"key":"D","text":"10"}]'::jsonb,
    'B','(6 + 8 + 10) ÷ 3 = 24 ÷ 3 = 8.',1,true),
  ('Português','Conjunções','Na frase "Eu estudaria mais, mas preciso trabalhar", a palavra "mas" indica:',
    '[{"key":"A","text":"adição"},{"key":"B","text":"oposição"},{"key":"C","text":"causa"},{"key":"D","text":"conclusão"}]'::jsonb,
    'B','"Mas" é uma conjunção adversativa e introduz ideia de oposição.',1,true),
  ('Português','Plural','Qual é o plural correto de "cidadão"?',
    '[{"key":"A","text":"cidadões"},{"key":"B","text":"cidadães"},{"key":"C","text":"cidadãos"},{"key":"D","text":"cidadãoes"}]'::jsonb,
    'C','O plural consagrado de "cidadão" é "cidadãos".',1,true),
  ('Português','Crase','Em qual alternativa o uso da crase está correto?',
    '[{"key":"A","text":"Vou à escola cedo."},{"key":"B","text":"Entreguei à ele o documento."},{"key":"C","text":"Cheguei à pé."},{"key":"D","text":"Fui à Brasília ontem."}]'::jsonb,
    'A','Há crase em "à escola" porque ocorre a fusão da preposição "a" com o artigo feminino "a".',2,true),
  ('História','Brasil Império','Em que ano foi proclamada a Independência do Brasil?',
    '[{"key":"A","text":"1789"},{"key":"B","text":"1808"},{"key":"C","text":"1822"},{"key":"D","text":"1889"}]'::jsonb,
    'C','A Independência do Brasil foi proclamada em 1822.',1,true),
  ('História','Brasil República','A Constituição brasileira conhecida como "Constituição Cidadã" foi promulgada em:',
    '[{"key":"A","text":"1946"},{"key":"B","text":"1967"},{"key":"C","text":"1985"},{"key":"D","text":"1988"}]'::jsonb,
    'D','A Constituição Federal vigente foi promulgada em 5 de outubro de 1988.',1,true),
  ('Geografia','Biomas','Qual é o maior bioma brasileiro em extensão territorial?',
    '[{"key":"A","text":"Cerrado"},{"key":"B","text":"Caatinga"},{"key":"C","text":"Amazônia"},{"key":"D","text":"Pampa"}]'::jsonb,
    'C','A Amazônia é o bioma de maior extensão no território brasileiro.',1,true),
  ('Biologia','Citologia','Qual organela está diretamente ligada à maior parte da produção de ATP na respiração celular?',
    '[{"key":"A","text":"Lisossomo"},{"key":"B","text":"Mitocôndria"},{"key":"C","text":"Complexo golgiense"},{"key":"D","text":"Ribossomo"}]'::jsonb,
    'B','As mitocôndrias realizam etapas centrais da respiração celular e produção de ATP.',1,true),
  ('Biologia','Genética','No DNA, a adenina se emparelha com qual base nitrogenada?',
    '[{"key":"A","text":"Citosina"},{"key":"B","text":"Guanina"},{"key":"C","text":"Timina"},{"key":"D","text":"Uracila"}]'::jsonb,
    'C','No DNA, adenina (A) se emparelha com timina (T).',1,true),
  ('Tecnologia','HTTP','O código HTTP 404 normalmente indica:',
    '[{"key":"A","text":"Acesso autorizado"},{"key":"B","text":"Recurso não encontrado"},{"key":"C","text":"Erro interno do servidor"},{"key":"D","text":"Redirecionamento permanente"}]'::jsonb,
    'B','O status 404 indica que o recurso solicitado não foi encontrado.',1,true),
  ('Tecnologia','Git','Qual comando moderno cria uma nova branch e já muda para ela?',
    '[{"key":"A","text":"git switch -c minha-branch"},{"key":"B","text":"git branch --delete minha-branch"},{"key":"C","text":"git pull -c minha-branch"},{"key":"D","text":"git status -c minha-branch"}]'::jsonb,
    'A','git switch -c cria a branch e muda o HEAD para ela.',2,true),
  ('Tecnologia','Web','Qual linguagem é usada para estruturar semanticamente o conteúdo de uma página web?',
    '[{"key":"A","text":"CSS"},{"key":"B","text":"HTML"},{"key":"C","text":"SQL"},{"key":"D","text":"JSON"}]'::jsonb,
    'B','HTML define a estrutura e a semântica do conteúdo de uma página web.',1,true)
on conflict (subject, coalesce(topic,''), statement) do update
set alternatives=excluded.alternatives,
    correct_answer=excluded.correct_answer,
    explanation=excluded.explanation,
    difficulty=excluded.difficulty,
    active=excluded.active;
